name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npm run cy:run

      - name: Generate HTML Report
        run: npm run cy:generate-html-report

      - name: Upload HTML Report
        uses: actions/upload-artifact@v2
        with:
          name: HTML Report
          path: reports/cucumber-htmlreport.html